version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - auth-postgres
      - rabbitmq
    env_file:
      - ./auth/.production.env

  parse:
    build:
      context: ./parse
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - comments-postgres
    env_file: ./comments/.production.env

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - user-postgres
    env_file:
      - ./user/.production.env

  workwithdb:
    build:
      context: ./workwithdb
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./workwithdb/.production.env

  user-postgres:
    image: postgres
    env_file:
      - ./user/.production.env
    ports:
      - "5433:5432"
    volumes:
      - ./user/dumps/userdump.sql:/docker-entrypoint-initdb.d/userdump.sql
      - userdata:/var/lib/postgresql/data/
    restart: on-failure

  comments-postgres:
    image: postgres
    env_file: ./comments/.production.env
    ports:
      - '5434:5432'
    volumes:
#      - ./comments/dumps/dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
      - comments-data:/var/lib/postgresql/data/
    restart: on-failure

  auth-postgres:
    image: postgres
    env_file:
      - ./auth/.production.env
    ports:
      - "5435:5432"
    volumes:
#      - ./auth/dumps/dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
      - authdata:/var/lib/postgresql/data/
    restart: on-failure

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  postgres:
    image: postgres
    env_file:
      - ./workwithdb/.production.env
    ports:
      - '5432:5432'
    volumes:
      - ./workwithdb/dumps/dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
      - kinopoisknew-parse-db:/var/lib/postgresql/data/
    restart: on-failure



volumes:
  authdata:
  userdata:
  kinopoisknew-parse-db:
  comments-data:


