version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '2fde7fd2'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'parse-base'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: always
volumes:
  postgres-data: