version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '2fde7fd2'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'kinopoisk-base'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

volumes:
  postgres-data: