version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .development.env

  postgres:
    image: postgres
    env_file:
      - .development.env
    ports:
      - '5432:5432'
    volumes:
      - ./dumps/dbdump.sql:/docker-entrypoint-initdb.d/dump.sql
      - /var/lib/postgresql/data/
    restart: on-failure




