version: '3'
services:
  api-gateway:
    build: ./../api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    env_file:
      - ./../api-gateway/.development.env

  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .development.env    

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  postgres:
    image: postgres
    env_file:
      - .development.env
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    restart: on-failure

volumes:
  pgdata:




